baseURL = '/'
locale = 'en-us'
title = 'Alisha Barretto'
theme = 'PaperMod'

enableRobotsTXT = true
buildDrafts = true
buildFuture = true

[params]
  env = 'production'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
